/**
 * This file is auto-generated by `generate-palette`
 * npm script. Do NOT edit manually.
 */

export const FLAVOUR_NAMES = ['latte', 'frappe', 'macchiato', 'mocha'] as const;
export const FLAVOUR_NAMES_PRETTY = [
  'Latte',
  'Frappé',
  'Macchiato',
  'Mocha',
] as const;
export const FLAVOUR_EMOJIS = ['🌻', '🪴', '🌺', '🌿'] as const;

export const ACCENT_COLOUR_NAMES = [
  'rosewater',
  'flamingo',
  'pink',
  'mauve',
  'red',
  'maroon',
  'peach',
  'yellow',
  'green',
  'teal',
  'sky',
  'sapphire',
  'blue',
  'lavender',
] as const;
export const NEUTRAL_COLOUR_NAMES = [
  'text',
  'subtext1',
  'subtext0',
  'overlay2',
  'overlay1',
  'overlay0',
  'surface2',
  'surface1',
  'surface0',
  'base',
  'mantle',
  'crust',
] as const;

export type FlavourName = (typeof FLAVOUR_NAMES)[number];
export type PrettyFlavourName = (typeof FLAVOUR_NAMES_PRETTY)[number];
export type FlavourEmoji = (typeof FLAVOUR_EMOJIS)[number];

export type ColourName = AccentColourName | NeutralColourName;
export type AccentColourName = (typeof ACCENT_COLOUR_NAMES)[number];
export type NeutralColourName = (typeof NEUTRAL_COLOUR_NAMES)[number];

export type FlavourPalette = Record<ColourName, `#${string}`>;
export type ColourPalette = Record<FlavourName, FlavourPalette>;

export const COLOURS_FLAVOUR_LATTE = {
  [ACCENT_COLOUR_NAMES[0]]: '#dc8a78',
  [ACCENT_COLOUR_NAMES[1]]: '#dd7878',
  [ACCENT_COLOUR_NAMES[2]]: '#ea76cb',
  [ACCENT_COLOUR_NAMES[3]]: '#8839ef',
  [ACCENT_COLOUR_NAMES[4]]: '#d20f39',
  [ACCENT_COLOUR_NAMES[5]]: '#e64553',
  [ACCENT_COLOUR_NAMES[6]]: '#fe640b',
  [ACCENT_COLOUR_NAMES[7]]: '#df8e1d',
  [ACCENT_COLOUR_NAMES[8]]: '#40a02b',
  [ACCENT_COLOUR_NAMES[9]]: '#179299',
  [ACCENT_COLOUR_NAMES[10]]: '#04a5e5',
  [ACCENT_COLOUR_NAMES[11]]: '#209fb5',
  [ACCENT_COLOUR_NAMES[12]]: '#1e66f5',
  [ACCENT_COLOUR_NAMES[13]]: '#7287fd',
  [NEUTRAL_COLOUR_NAMES[0]]: '#4c4f69',
  [NEUTRAL_COLOUR_NAMES[1]]: '#5c5f77',
  [NEUTRAL_COLOUR_NAMES[2]]: '#6c6f85',
  [NEUTRAL_COLOUR_NAMES[3]]: '#7c7f93',
  [NEUTRAL_COLOUR_NAMES[4]]: '#8c8fa1',
  [NEUTRAL_COLOUR_NAMES[5]]: '#9ca0b0',
  [NEUTRAL_COLOUR_NAMES[6]]: '#acb0be',
  [NEUTRAL_COLOUR_NAMES[7]]: '#bcc0cc',
  [NEUTRAL_COLOUR_NAMES[8]]: '#ccd0da',
  [NEUTRAL_COLOUR_NAMES[9]]: '#eff1f5',
  [NEUTRAL_COLOUR_NAMES[10]]: '#e6e9ef',
  [NEUTRAL_COLOUR_NAMES[11]]: '#dce0e8',
} as const satisfies FlavourPalette;
export const COLOURS_FLAVOUR_FRAPPE = {
  [ACCENT_COLOUR_NAMES[0]]: '#f2d5cf',
  [ACCENT_COLOUR_NAMES[1]]: '#eebebe',
  [ACCENT_COLOUR_NAMES[2]]: '#f4b8e4',
  [ACCENT_COLOUR_NAMES[3]]: '#ca9ee6',
  [ACCENT_COLOUR_NAMES[4]]: '#e78284',
  [ACCENT_COLOUR_NAMES[5]]: '#ea999c',
  [ACCENT_COLOUR_NAMES[6]]: '#ef9f76',
  [ACCENT_COLOUR_NAMES[7]]: '#e5c890',
  [ACCENT_COLOUR_NAMES[8]]: '#a6d189',
  [ACCENT_COLOUR_NAMES[9]]: '#81c8be',
  [ACCENT_COLOUR_NAMES[10]]: '#99d1db',
  [ACCENT_COLOUR_NAMES[11]]: '#85c1dc',
  [ACCENT_COLOUR_NAMES[12]]: '#8caaee',
  [ACCENT_COLOUR_NAMES[13]]: '#babbf1',
  [NEUTRAL_COLOUR_NAMES[0]]: '#c6d0f5',
  [NEUTRAL_COLOUR_NAMES[1]]: '#b5bfe2',
  [NEUTRAL_COLOUR_NAMES[2]]: '#a5adce',
  [NEUTRAL_COLOUR_NAMES[3]]: '#949cbb',
  [NEUTRAL_COLOUR_NAMES[4]]: '#838ba7',
  [NEUTRAL_COLOUR_NAMES[5]]: '#737994',
  [NEUTRAL_COLOUR_NAMES[6]]: '#626880',
  [NEUTRAL_COLOUR_NAMES[7]]: '#51576d',
  [NEUTRAL_COLOUR_NAMES[8]]: '#414559',
  [NEUTRAL_COLOUR_NAMES[9]]: '#303446',
  [NEUTRAL_COLOUR_NAMES[10]]: '#292c3c',
  [NEUTRAL_COLOUR_NAMES[11]]: '#232634',
} as const satisfies FlavourPalette;
export const COLOURS_FLAVOUR_MACCHIATO = {
  [ACCENT_COLOUR_NAMES[0]]: '#f4dbd6',
  [ACCENT_COLOUR_NAMES[1]]: '#f0c6c6',
  [ACCENT_COLOUR_NAMES[2]]: '#f5bde6',
  [ACCENT_COLOUR_NAMES[3]]: '#c6a0f6',
  [ACCENT_COLOUR_NAMES[4]]: '#ed8796',
  [ACCENT_COLOUR_NAMES[5]]: '#ee99a0',
  [ACCENT_COLOUR_NAMES[6]]: '#f5a97f',
  [ACCENT_COLOUR_NAMES[7]]: '#eed49f',
  [ACCENT_COLOUR_NAMES[8]]: '#a6da95',
  [ACCENT_COLOUR_NAMES[9]]: '#8bd5ca',
  [ACCENT_COLOUR_NAMES[10]]: '#91d7e3',
  [ACCENT_COLOUR_NAMES[11]]: '#7dc4e4',
  [ACCENT_COLOUR_NAMES[12]]: '#8aadf4',
  [ACCENT_COLOUR_NAMES[13]]: '#b7bdf8',
  [NEUTRAL_COLOUR_NAMES[0]]: '#cad3f5',
  [NEUTRAL_COLOUR_NAMES[1]]: '#b8c0e0',
  [NEUTRAL_COLOUR_NAMES[2]]: '#a5adcb',
  [NEUTRAL_COLOUR_NAMES[3]]: '#939ab7',
  [NEUTRAL_COLOUR_NAMES[4]]: '#8087a2',
  [NEUTRAL_COLOUR_NAMES[5]]: '#6e738d',
  [NEUTRAL_COLOUR_NAMES[6]]: '#5b6078',
  [NEUTRAL_COLOUR_NAMES[7]]: '#494d64',
  [NEUTRAL_COLOUR_NAMES[8]]: '#363a4f',
  [NEUTRAL_COLOUR_NAMES[9]]: '#24273a',
  [NEUTRAL_COLOUR_NAMES[10]]: '#1e2030',
  [NEUTRAL_COLOUR_NAMES[11]]: '#181926',
} as const satisfies FlavourPalette;
export const COLOURS_FLAVOUR_MOCHA = {
  [ACCENT_COLOUR_NAMES[0]]: '#f5e0dc',
  [ACCENT_COLOUR_NAMES[1]]: '#f2cdcd',
  [ACCENT_COLOUR_NAMES[2]]: '#f5c2e7',
  [ACCENT_COLOUR_NAMES[3]]: '#cba6f7',
  [ACCENT_COLOUR_NAMES[4]]: '#f38ba8',
  [ACCENT_COLOUR_NAMES[5]]: '#eba0ac',
  [ACCENT_COLOUR_NAMES[6]]: '#fab387',
  [ACCENT_COLOUR_NAMES[7]]: '#f9e2af',
  [ACCENT_COLOUR_NAMES[8]]: '#a6e3a1',
  [ACCENT_COLOUR_NAMES[9]]: '#94e2d5',
  [ACCENT_COLOUR_NAMES[10]]: '#89dceb',
  [ACCENT_COLOUR_NAMES[11]]: '#74c7ec',
  [ACCENT_COLOUR_NAMES[12]]: '#89b4fa',
  [ACCENT_COLOUR_NAMES[13]]: '#b4befe',
  [NEUTRAL_COLOUR_NAMES[0]]: '#cdd6f4',
  [NEUTRAL_COLOUR_NAMES[1]]: '#bac2de',
  [NEUTRAL_COLOUR_NAMES[2]]: '#a6adc8',
  [NEUTRAL_COLOUR_NAMES[3]]: '#9399b2',
  [NEUTRAL_COLOUR_NAMES[4]]: '#7f849c',
  [NEUTRAL_COLOUR_NAMES[5]]: '#6c7086',
  [NEUTRAL_COLOUR_NAMES[6]]: '#585b70',
  [NEUTRAL_COLOUR_NAMES[7]]: '#45475a',
  [NEUTRAL_COLOUR_NAMES[8]]: '#313244',
  [NEUTRAL_COLOUR_NAMES[9]]: '#1e1e2e',
  [NEUTRAL_COLOUR_NAMES[10]]: '#181825',
  [NEUTRAL_COLOUR_NAMES[11]]: '#11111b',
} as const satisfies FlavourPalette;

export const COLOURS = {
  [FLAVOUR_NAMES[0]]: COLOURS_FLAVOUR_LATTE,
  [FLAVOUR_NAMES[1]]: COLOURS_FLAVOUR_FRAPPE,
  [FLAVOUR_NAMES[2]]: COLOURS_FLAVOUR_MACCHIATO,
  [FLAVOUR_NAMES[3]]: COLOURS_FLAVOUR_MOCHA,
} as const satisfies ColourPalette;
